- type: job
  id: Service
  name: job-name-service
  description: job-description-Service
  playTimeTracker: JobService
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  whitelisted: false
  startingGear: ServiceGear
  alwaysUseSpawner: true
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-sr
  weight: 170
  displayWeight: 55 # Second from the top
  canBeAntag: false
  accessGroups:
  - GeneralAccess
  - Service
  special:
  - !type:AddImplantSpecial
    implants: [ TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: ServiceGear
  storage:
    back:
    - EncryptionKeyService # Frontier
